    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment  # Use a clear name
    spec:
      replicas: 1   # Single replica to save resources
      selector:
        matchLabels:
          app: nginx-app
      template:
        metadata:
          labels:
            app: nginx-app
        spec:
          containers:
            - name: nginx
              image: nginx:alpine  # <-- THIS IS A REAL, LIGHTWEIGHT IMAGE
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
    
