apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default # <-- NEW: Specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
--- # Start of Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default # <-- NEW: Specify the namespace
spec:
  type: LoadBalancer 
  selector:
    app: nginx-app 
  ports:
    - name: http
      protocol: TCP
      port: 80     
      targetPort: 80 
